POST https://node-drab-ten.vercel.app/videos
Content-Type: application/json

{
    "title": "video node",
    "description": "esse é o 1",
    "duration": 100
}


###

GET https://node-drab-ten.vercel.app/videos


###
PUT https://node-drab-ten.vercel.app/videos/e9554112-b27a-4c57-b727-d6c81d3bb987
Content-Type: application/json

{
    "title": "video 2",
    "description": "esse é o 2",
    "duration": 100
}

###


DELETE https://node-drab-ten.vercel.app/videos/e9554112-b27a-4c57-b727-d6c81d3bb987
